version: '3.7'

services:

  reverse-proxy:
    image: jheilbut/composr-reverseproxy
    container_name: composr-reverseproxy
    # restart: on-failure
    ports:
      - "8084:8084"
    environment:
      - VERSION=latest
  
  api:
    depends_on:
      - reverse-proxy
    image: jheilbut/composr
    container_name: composr-api
    # restart: on-failure
    # ports:
    #   - "3000:3000"
    environment:
      - VERSION=latest

  client:
    depends_on:
      - reverse-proxy
    image: jheilbut/composr-client
    container_name: composr-client
    # restart: on-failure
    # ports:
    #   - "9191:80"
    environment:
      - VERSION=latest
