version: '3.3'

services:

  web: 
    image: jheilbut/composr
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - 8084:3000
    environment:
      VERSION: latest

# Run this command in Powershell   
# docker -H devdocker:2376 stack deploy -c C:\source\doi\composr\api\composr.yml composr
# This is a file location on the network for my stuff
# \\inf-fs01\docker\jeff
            